### ISSUE TITLE
keep getting a /who of everyone who talks in a *world chat channel

### ISSUE THREAD

**Issue by ldrancer** [benjamingorman/Prat#2]
i dont know i keep getting the program using who i downloaded this one right here.  everyone who talks in the chat, it who's everyone.  if more than one result shows up, it pops up the who box.  with the results.   it does this non-stop, unless its timed out.  i liked some of the stuff it does but i just cant use it.  ive toggled the who disabled and enabled.

**Comment by benjamingorman** [comment]
This is my personal fork of Prat. It would be better to submit your issue to the official repo.
